[package]
name = "solana_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
ic-stable-structures = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 